zuul:
  routes:
    recipe:
      path: /recipe/**
      serviceId: recipe
    restaurant:
      ribbon:
        NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
        listOfServers: https://example1.com,http://example2.com
        ConnectTimeout: 1000
        ReadTimeout: 3000
        MaxTotalHttpConnections: 500
        MaxConnectionsPerHost: 100
      path: /restaurant/**
      serviceId: restaurant
  sensitive-headers:
    - Cookie,Set-Cookie

eureka:
 client:
   registerWithEureka: false
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/
server:
  port: 6565

logging:
  level:
    org.springframework: ERROR
