zuul:
  routes:
    recipe:
      path: /recipe/**
      serviceId: recipe
    restaurant:
      path: /restaurant/**
      serviceId: restaurant
eureka:
 client:
   registerWithEureka: false
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/
server:
  port: 6565